import img1 from "./utils/b-11.jpg.svg";
import img2 from "./utils/b-11.jpg (8).svg";
import img3 from "./utils/b-11.jpg (1).svg";
import img4 from "./utils/b-11.jpg (2).svg";
import img5 from "./utils/b-11.jpg (3).svg";
import img6 from "./utils/b-11.jpg (4).svg";
import img7 from "./utils/b-11.jpg (5).svg";
import img8 from "./utils/b-11.jpg (6).svg";
import img9 from "./utils/b-11.jpg (7).svg";
import img10 from "./utils/Contemporary Style House Plan - 3 Beds 2_5 Baths….jpeg";
import img11 from "./utils/Discover the charm and convenience of prefab homes….jpeg";
import img12 from "./utils/efb164e4-b0f7-4eca-a366-4e11d834c457.jpeg";
import img13 from "./utils/luxury.jpg";
import img14 from "./utils/3af1446f-99c6-4bea-bb46-ef7d9a94c829.jpg";
import img15 from "./utils/Black or white_.jpg";

const shows = [
  {
    id: 1,
    image: img1,
    whatFor: "Sale",
    title: "Real House Luxury Villa",
    location: "Victoria Island, Lagos",
    bed: 6,
    bath: 3,
    price: "3,340,000",
    amount: 3340000,
    images: [
      "../src/utils/extra/kitchen1.jpg",
      "../src/utils/extra/bedroom1.jpg",
      "../src/utils/extra/bathroom1.jpg",
    ],
  },
  {
    id: 2,
    image: img2,
    whatFor: "Rent",
    title: "Exquisite Haven Villa",
    location: "Festac, Lagos",
    bed: 5,
    bath: 3,
    price: "4,000,000",
    amount: 4000000,
    images: [
      "../src/utils/extra/kitchen2.jpg",
      "../src/utils/extra/bedroom2.jpg",
      "../src/utils/extra/bathroom2.jpg",
    ],
  },
  {
    id: 3,
    image: img3,
    whatFor: "Sale",
    title: "Luxe Palatial Villa",
    location: "Gbagada, Lagos",
    bed: 7,
    bath: 3,
    price: "5,350,000",
    amount: 5350000,
    images: [
      "../src/utils/extra/kitchen3.jpg",
      "../src/utils/extra/bedroom3.jpg",
      "../src/utils/extra/bathroom3.jpg",
    ],
  },
  {
    id: 4,
    image: img4,
    whatFor: "Rent",
    title: "Harmony Luxury Villa",
    location: "Mushin, Lagos",
    bed: 4,
    bath: 3,
    price: "4,000,000",
    amount: 4000000,
    images: [
      "../src/utils/extra/kitchen4.jpg",
      "../src/utils/extra/bedroom4.jpg",
      "../src/utils/extra/bathroom4.jpg",
    ],
  },
  {
    id: 5,
    image: img5,
    whatFor: "Rent",
    title: "Real House Luxury Villa",
    location: "Victoria Island, Lagos",
    bed: 6,
    bath: 4,
    price: "3,500,000",
    amount: 3500000,
    images: [
      "../src/utils/extra/kitchen5.jpg",
      "../src/utils/extra/bedroom5.jpg",
      "../src/utils/extra/bathroom5.jpg",
    ],
  },
  {
    id: 6,
    image: img6,
    whatFor: "Sale",
    title: "Real House Luxury Villa",
    location: "Lekki-Ajah, Lagos",
    bed: 5,
    bath: 3,
    price: "4,000,000",
    amount: 4000000,
    images: [
      "../src/utils/extra/kitchen6.jpg",
      "../src/utils/extra/bedroom6.jpg",
      "../src/utils/extra/bathroom6.jpg",
    ],
  },
  {
    id: 7,
    image: img7,
    whatFor: "Sale",
    title: "Infinite Bliss Villa",
    location: "Ishiagu, Enugu",
    bed: 5,
    bath: 3,
    price: "25,000,000",
    amount: 25000000,
    images: [
      "../src/utils/extra/kitchen7.jpg",
      "../src/utils/extra/bedroom7.jpg",
      "../src/utils/extra/bathroom7.jpg",
    ],
  },
  {
    id: 8,
    image: img8,
    whatFor: "Rent",
    title: "Real House Luxury Villa",
    location: "Works Layout, Owerri",
    bed: 8,
    bath: 6,
    price: "3,350,000",
    amount: 3350000,
    images: [
      "../src/utils/extra/kitchen8.jpg",
      "../src/utils/extra/bedroom8.jpg",
      "../src/utils/extra/bathroom8.jpg",
    ],
  },
  {
    id: 9,
    image: img9,
    whatFor: "Sale",
    title: "Real House Luxury Villa",
    location: "Ikeja, Lagos",
    bed: 6,
    bath: 6,
    price: "60,000,000",
    amount: 60000000,
    images: [
      "../src/utils/extra/kitchen9.jpg",
      "../src/utils/extra/bedroom9.jpg",
      "../src/utils/extra/bathroom9.jpg",
    ],
  },
  {
    id: 10,
    image: img10,
    whatFor: "Sale",
    title: "Harmony Luxury Villa",
    location: "Ikeja, Lagos",
    bed: 5,
    bath: 3,
    price: "7,000,000",
    amount: 7000000,
    images: [
      "../src/utils/extra/kitchen10.jpg",
      "../src/utils/extra/bedroom10.jpg",
      "../src/utils/extra/bathroom10.jpg",
    ],
  },
  {
    id: 11,
    image: img11,
    whatFor: "Rent",
    title: "Infinite Bliss Villa",
    location: "Works Layout, Owerri",
    bed: 8,
    bath: 3,
    price: "100,000,000",
    amount: 100000000,
    images: [
      "../src/utils/extra/kitchen11.jpg",
      "../src/utils/extra/bedroom11.jpg",
      "../src/utils/extra/bathroom11.jpg",
    ],
  },
  {
    id: 12,
    image: img12,
    whatFor: "Rent",
    title: "Real House Luxury Villa",
    location: "Gbadaga, Lagos",
    bed: 4,
    bath: 3,
    price: "15,000,000",
    amount: 15000000,
    images: [
      "../src/utils/extra/kitchen12.jpg",
      "../src/utils/extra/bedroom12.jpg",
      "../src/utils/extra/bathroom12.jpg",
    ],
  },
  {
    id: 13,
    image: img13,
    whatFor: "Sale",
    title: "Luxe Palatial Villa",
    location: "Lekki-Ajah, Lagos",
    bed: 4,
    bath: 4,
    price: "9,000,000",
    amount: 9000000,
    images: [
      "../src/utils/extra/kitchen13.jpg",
      "../src/utils/extra/bedroom13.jpg",
      "../src/utils/extra/bathroom13.jpg",
    ],
  },
  {
    id: 14,
    image: img14,
    whatFor: "Sale",
    title: "Exquisite Haven Villa",
    location: "Ishiagu, Enugu",
    bed: 6,
    bath: 3,
    price: "90,000,000",
    amount: 90000000,
    images: [
      "../src/utils/extra/kitchen14.jpg",
      "../src/utils/extra/bedroom14.jpg",
      "../src/utils/extra/sitingRoom1.jpg",
    ],
  },
  {
    id: 15,
    image: img15,
    whatFor: "Rent",
    title: "Infinite Bliss Villa",
    location: "Mushin, Lagos",
    bed: 5,
    bath: 3,
    price: "2,380,000",
    amount: 2380000,
    images: [
      "../src/utils/extra/bathroom12.jpg",
      "../src/utils/extra/kitchen14.jpg",
      "../src/utils/extra/sittingRoom13.jpg.jpg",
    ],
  },
];

export default shows;
